# Generated by Django 6.0.3 on 2026-06-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
